# -*- coding: utf-8 -*-
"""ECT_HW2_104403553_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I_f5fcD1VTpf8qJLW4NKxB9wGPKQNAiC

# ECT_HW2_104403553_v1

### import 需要的一些packages，graphviz 拿來畫圖用的
"""

import pandas as pd
import graphviz
from sklearn import preprocessing
from sklearn import tree
from sklearn import metrics

"""### 讀glass.csv近來"""

data = pd.read_csv('glass.csv')

"""### 將讀進來的資料分為input跟output
* x 是input<br>
* y 是output: type
"""

#x:input
x=data.loc[:,['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']]
#y:output
y=data.loc[:,['Type']]

"""### 將Type轉成label"""

le = preprocessing.LabelEncoder()
Y_glass_label = le.fit_transform(y.Type)

feature=list(zip(x.RI, x.Na, x.Mg, x.Al, x.Si, x.K, x.Ca, x.Ba, x.Fe))
import numpy as np
features=np.asarray(feature)

"""### 將dataset 切出 training set,test set出來"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, Y_glass_label, test_size=0.34)

"""### train 出那棵樹"""

clf = tree.DecisionTreeClassifier(criterion = 'entropy',max_depth=3,max_leaf_nodes = 4)
glass_clf = clf.fit(X_train,y_train)

"""### 驗證剛剛train的樹的準確度"""

predicted_train = glass_clf.predict(X_train)
accuracy_train = metrics.accuracy_score(predicted_train, y_train)
print('accuracy train ')
print(accuracy_train)
predicted_test = glass_clf.predict(X_test)
accuracy_test = metrics.accuracy_score(predicted_test, y_test)
print('accuracy test')
print(accuracy_test)

"""### 用graphviz來視覺化那棵樹"""

dot_data = tree.export_graphviz(clf, out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("glass")

graph

